#!/usr/bin/env bash
# Install the standing agent rules into every coding agent on this machine.
#
# Sources are the bodies in this directory, one per rule:
#   knowledge-base.md         routes work questions to kb/ and says when to capture
#   response-preferences.md   whose side the agent is on, and how responses are formatted
#   engineering-principles.md how work gets done and verified
#
# Bodies say {{KB_ROOT}} wherever they mean this repo, so the same text works
# wherever it is cloned. Everything else is rendered from them into
# setup/.generated/ (git-ignored, since it holds your machine's paths):
#   Cursor       -> .generated/<rule>.mdc, copied to $CURSOR_RULES_DIR
#                   (default: <parent of this repo>/.cursor/rules/, i.e. the
#                   workspace root when the repo sits one level below it)
#   Claude Code  -> ~/.claude/CLAUDE.md imports each .generated/<rule>.md
#   Codex        -> ~/.codex/AGENTS.md is generated by concatenating the bodies
#   Cursor hooks -> .generated/hooks.json, to merge into ~/.cursor/hooks.json
#
# Re-run after editing any body. Idempotent; prints what it did.
# `--check` verifies the installed copies match without changing anything.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$HERE")"
KB_ROOT="${REPO/#$HOME/~}"
OUT="$HERE/.generated"
CURSOR_RULES_DIR="${CURSOR_RULES_DIR:-$(dirname "$REPO")/.cursor/rules}"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
CODEX_AGENTS="$HOME/.codex/AGENTS.md"
CODEX_MARKER="<!-- generated by $KB_ROOT/setup/install.sh -- edit the bodies in setup/, not this file -->"

# Each rule: <slug>|<Cursor description>. Order is the order Codex reads them in.
RULES=(
  "knowledge-base|Routes questions about personal work knowledge to the personal knowledge base"
  "response-preferences|Whose side you're on, and how responses are formatted — visual where possible, concise everywhere"
  "engineering-principles|How work gets done: prove it against the real artifact, build the lever, encode repeated corrections in structure"
)

check_only=0
[[ "${1:-}" == "--check" ]] && check_only=1

status=0
report() { printf '%-12s %s\n' "$1" "$2"; }

render() {  # $1 = template path; substitutes {{KB_ROOT}}
  sed "s|{{KB_ROOT}}|$KB_ROOT|g" "$1"
}

render_mdc() {  # $1 = slug, $2 = description
  printf -- '---\ndescription: %s\nalwaysApply: true\n---\n\n' "$2"
  render "$HERE/$1.md"
}

render_codex() {
  printf '%s\n\n' "$CODEX_MARKER"
  local first=1 rule slug
  for rule in "${RULES[@]}"; do
    slug="${rule%%|*}"
    [[ $first -eq 0 ]] && printf '\n---\n\n'
    first=0
    render "$HERE/$slug.md"
  done
}

same() {  # $1 = expected content (from a process substitution), $2 = file
  diff -q "$1" "$2" >/dev/null 2>&1
}

[[ $check_only -eq 0 ]] && mkdir -p "$OUT"

# --- Rendered bodies, and the Cursor rules derived from them -----------------
for rule in "${RULES[@]}"; do
  slug="${rule%%|*}"; desc="${rule#*|}"
  mdc="$OUT/$slug.mdc"
  if [[ $check_only -eq 1 ]]; then
    if same <(render "$HERE/$slug.md") "$OUT/$slug.md" && same <(render_mdc "$slug" "$desc") "$mdc"; then
      report render "$slug up to date"
    else
      report render "$slug STALE (run install.sh)"; status=1
    fi
    if same "$mdc" "$CURSOR_RULES_DIR/$slug.mdc"; then
      report cursor "$slug installed copy matches"
    else
      report cursor "$slug installed copy MISSING or differs in $CURSOR_RULES_DIR"; status=1
    fi
  else
    render "$HERE/$slug.md" > "$OUT/$slug.md"
    render_mdc "$slug" "$desc" > "$mdc"
    mkdir -p "$CURSOR_RULES_DIR"
    cp "$mdc" "$CURSOR_RULES_DIR/$slug.mdc"
    report cursor "wrote $CURSOR_RULES_DIR/$slug.mdc"
  fi
done

# --- Cursor hooks: rendered for you to merge, never written over yours -------
if [[ $check_only -eq 1 ]]; then
  if same <(render "$HERE/hooks/hooks.json") "$OUT/hooks.json"; then
    report hooks "hooks.json up to date"
  else
    report hooks "hooks.json STALE (run install.sh)"; status=1
  fi
else
  render "$HERE/hooks/hooks.json" > "$OUT/hooks.json"
  report hooks "wrote $OUT/hooks.json; merge into ~/.cursor/hooks.json (see setup/README.md)"
fi

# --- Claude Code: one import line per body in the user-level CLAUDE.md -------
[[ $check_only -eq 0 ]] && mkdir -p "$(dirname "$CLAUDE_MD")"
for rule in "${RULES[@]}"; do
  slug="${rule%%|*}"
  line="@$KB_ROOT/setup/.generated/$slug.md"
  if [[ $check_only -eq 1 ]]; then
    if grep -qxF "$line" "$CLAUDE_MD" 2>/dev/null; then
      report claude "$slug import present"
    else
      report claude "$slug import MISSING in $CLAUDE_MD"; status=1
    fi
  else
    if ! grep -qxF "$line" "$CLAUDE_MD" 2>/dev/null; then
      { [[ -s "$CLAUDE_MD" ]] && printf '\n'; printf '%s\n' "$line"; } >> "$CLAUDE_MD"
      report claude "appended $slug import to $CLAUDE_MD"
    else
      report claude "$slug import already present"
    fi
  fi
done

# --- Claude Code: SessionStart hook that keeps aging markers fresh -----------
# The markers only move when `kb.py sync` runs, and nobody remembers to run it.
# A session start is the cheapest moment to try; the script self-throttles to
# once every twelve hours and fails open, so this is close to free.
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
AUTOSYNC_CMD="python3 $HERE/hooks/kb-autosync.py"

sync_hook() {  # $1 = "check" | "write"
  python3 - "$CLAUDE_SETTINGS" "$AUTOSYNC_CMD" "$1" <<'PYEOF'
import json, os, shutil, sys
path, cmd, mode = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    data = json.load(open(path)) if os.path.exists(path) else {}
except Exception:
    print("unreadable"); sys.exit(2)
matchers = data.get("hooks", {}).get("SessionStart", [])
present = any(
    h.get("command") == cmd
    for m in matchers if isinstance(m, dict)
    for h in m.get("hooks", [])
)
if mode == "check":
    print("present" if present else "missing"); sys.exit(0 if present else 1)
if present:
    print("already present"); sys.exit(0)
if os.path.exists(path):
    shutil.copy2(path, path + ".bak")
data.setdefault("hooks", {}).setdefault("SessionStart", []).append(
    {"hooks": [{"type": "command", "command": cmd}]}
)
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as fh:
    json.dump(data, fh, indent=2)
    fh.write("\n")
print("added")
PYEOF
}

if [[ $check_only -eq 1 ]]; then
  out="$(sync_hook check || true)"
  if [[ "$out" == "present" ]]; then report autosync "SessionStart hook present"; else report autosync "SessionStart hook $out"; status=1; fi
else
  out="$(sync_hook write || true)"
  report autosync "$out (SessionStart -> kb-autosync.py)"
fi

# --- Codex: global AGENTS.md generated from all the bodies -------------------
if [[ $check_only -eq 1 ]]; then
  if same <(render_codex) "$CODEX_AGENTS"; then
    report codex "up to date"
  else
    report codex "STALE, MISSING, or hand-edited (run install.sh)"; status=1
  fi
else
  mkdir -p "$(dirname "$CODEX_AGENTS")"
  if [[ -f "$CODEX_AGENTS" && ! -L "$CODEX_AGENTS" ]] && ! grep -qF "$CODEX_MARKER" "$CODEX_AGENTS"; then
    report codex "$CODEX_AGENTS exists and was not generated here; merge by hand, not overwriting"
    status=1
  else
    rm -f "$CODEX_AGENTS"
    render_codex > "$CODEX_AGENTS"
    report codex "wrote $CODEX_AGENTS from ${#RULES[@]} bodies"
  fi
fi

exit $status
